@tool
extends EditorScript
class_name BuildResourceRegistries

#Output paths for the generated registry files
const ITEM_OUTPUT_PATH = "res://DataFiles/Generated/ItemPreloadRegistry.gd";
const HARVESTABLE_OUTPUT_PATH = "res://DataFiles/Generated/HarvestablePreloadRegistry.gd";
const ENEMY_OUTPUT_PATH = "res://DataFiles/Generated/EnemyPreloadRegistry.gd";
const DIALOGUE_OUTPUT_PATH = "res://DataFiles/Generated/DialoguePreloadRegistry.gd";
const QUEST_OUTPUT_PATH = "res://DataFiles/Generated/QuestPreloadRegistry.gd";
const NPC_OUTPUT_PATH = "res://DataFiles/Generated/NPCPreloadRegistry.gd";
const RECIPES_OUTPUT_PATH = "res://DataFiles/Generated/RecipePreloadRegistry.gd";
#Source folders — must match what the databases currently scan
const ITEMS_FOLDER = "res://Entities/Items/Resources/";
const HARVESTABLES_FOLDER = "res://Entities/Harvestables/Resources/";
const ENEMIES_FOLDER = "res://Entities/Enemies/Resources/";
const DIALOGUE_FOLDER = "res://UI/Resources/Dialogue/";
const QUESTS_FOLDER = "res://UI/Resources/Quests/";
const NPCS_FOLDER = "res://Entities/NPCs/Resources/";
const RECIPES_FOLDER = "res://UI/Resources/Crafting/"

func _run() -> void:
	var errors: int = 0;
	var warnings: int = 0;
	
	#Items registry
	var r1 := _build_registry(ITEMS_FOLDER, ITEM_OUTPUT_PATH,"ItemPreloadRegistry");
	errors += r1.errors;
	warnings += r1.warnings;
	
	#Harvestables registry
	var r2 := _build_registry(HARVESTABLES_FOLDER, HARVESTABLE_OUTPUT_PATH, "HarvestablePreloadRegistry");
	errors += r2.errors;
	warnings += r2.warnings;
	
	#Enemies registry
	var r3 := _build_registry(ENEMIES_FOLDER, ENEMY_OUTPUT_PATH, "EnemyPreloadRegistry");
	errors += r3.errors;
	warnings += r3.warnings;
	
	#Dialogue registry
	var r4 := _build_registry(DIALOGUE_FOLDER, DIALOGUE_OUTPUT_PATH, "DialoguePreloadRegistry");
	errors += r4.errors;
	warnings += r4.warnings;
	
	#Quests registry
	var r5 := _build_registry(QUESTS_FOLDER, QUEST_OUTPUT_PATH, "QuestPreloadRegistry");
	errors += r5.errors;
	warnings += r5.warnings;
	
	#NPC registry
	var r6 := _build_registry(NPCS_FOLDER, NPC_OUTPUT_PATH, "NPCPreloadRegistry");
	errors += r6.errors;
	warnings += r6.warnings;
	
	#Crafting
	var r7 := _build_registry(RECIPES_FOLDER, RECIPES_OUTPUT_PATH, "RecipesPreloadRegistry");
	errors += r7.errors;
	warnings += r7.warnings;
	
	print("BuildResourceRegistries: Done. errors=%d warnigs=%d" % [errors, warnings]);

func _build_registry(folder_path: String, output_path: String, class_label: String) -> Dictionary:
	var result: Dictionary = { "errors": 0, "warnings": 0 };
	
	#Get the resources pass
	var paths := _collect_resource_paths(folder_path);
	if paths.is_empty():
		push_warning("BuildResourceRegistries(%s): No .tres/.res files found in %s" % [class_label, folder_path])
		result.warnings += 1;
		#Still write an empty registry so the databases don't break
	
	#Build the file contents
	var lines: PackedStringArray = [];
	lines.append("#AUTO-GENERATED by BuildResourceRegistries.gd — do not edit by hand.");
	lines.append("#Re-run EditorTools/BuildResourceRegistries.gd whenever adding or eemoving resources.");
	lines.append("extends RefCounted");
	lines.append("class_name %s" % class_label);
	lines.append("");
	lines.append("const ALL: Array = [");
	for p in paths:
		lines.append("\tpreload(\"%s\")," % p);
	lines.append("]");
	lines.append("");
	
	var content := "\n".join(lines);
	
	#Ensure the output folder exists
	var dir := DirAccess.open("res://");
	if not dir.dir_exists("res://DataFiles/Generated"):
		dir.make_dir_recursive("res://DataFiles/Generated");
		
	var f := FileAccess.open(output_path, FileAccess.WRITE);
	if f == null:
		result.errors += 1;
		push_error("BuildResourceRegistries(%s): Could not write to %s" % [class_label, output_path])
		return result;

	f.store_string(content);
	f.flush();
	print("BuildResourceRegistries(%s): Wrote %d entries to %s" % [class_label, paths.size(), output_path]);
	return result;

func _collect_resource_paths(folder_path: String) -> Array:
	var paths: Array = [];
	var dir := DirAccess.open(folder_path);
	if dir == null:
		push_error("BuildResourceRegistries: Could not open folder: %s" % folder_path);
		return paths;
		
	dir.list_dir_begin();
	var file_name := dir.get_next();
	while file_name != "":
		if not dir.current_is_dir():
			if file_name.ends_with(".tres") or file_name.ends_with(".res"):
				paths.append(folder_path + file_name);
		file_name = dir.get_next();
	dir.list_dir_end();
	
	paths.sort(); #Deterministic output so git diffs are clean
	return paths;
